name: Node Continuous Integration

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node_version: '16'
          # cache: 'npm'
          # cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run coverage
      - name: Run build
        run: npm run build
