name: Node Continuous Integration

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node_version: 16
      - run: npm ci
      - run: npm run coverage
      - run: npm run build
