name: Node Continuous Integration

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node_version: '16'
          # cache: 'npm'
          # cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run coverage
      - run: npm run build
